### PR TITLE
Add Message::header

### PR DESCRIPTION
**Pull request by rhn**
Adds the ability to get a header from a function. Add unspecified error value, because notmuch doesn't offer a detailed one :(

### CODE REVIEW

**Comment by vhdirk** [comment]
I'd opt for a more generic error. ```notmuch_message_get_header``` isn't the only function that returns ```NULL``` on error. ```notmuch_database_get_all_tags``` does that as well.

**Comment by rhn** [comment]
Turned into UnspecifiedError. I wanted to make it reference Notmuch in the name, but that would get confused with the other error.

**Comment by vhdirk** [comment]
I'm never going to like that there's no way to know what exactly went wrong, but that's beyond the scope of the issue. Looks good to me.

**Comment by rhn** [comment]
Same here. Seeing that other functions all return something sane, I was rather surprised about this one. Skimming through API docs, I didn't catch that `get_all_tags is defective in the same way...

As a ray of hope, notmuch API changed over time to cover similar cases. Here's to hoping that someone will live up to the task of fixing the remaining problems.

**Comment by vhdirk** [comment]
That't be nice, yes.
Off-topic: Since you currently seem the only other user of this crate; Do you need thread safety? I've already wrapped the pointers in Rc's, but some tasks are inherently slow. For instance, ```notmuch_query_count_threads``` could take a couple of seconds. I was thinking of replacing the Rc's with Arcs and Mutexes, but I'm not sure if that wouldn't introduce too much overhead.

**Comment by rhn** [comment]
I kind of assumed that notmuch would not be thread-safe, since it's a low-level library, and locks are slow.
I would definitely prefer it to be fast and to let the user wrap things. Which I do too, because that's required by QML bindings, alas.

**Comment by rhn** [comment]
By the way, does using `Rc`s make things like iterating over messages slower than when using references?

**Comment by vhdirk** [comment]
Not really. Or to put it differently: I haven't noticed any performance hit. The reason I put these ````Rc```s in place is that lifetimes are only applicable to the stack. Since internally we're tracking C pointers, stack lifetime is way less important. The data lives on the heap anyway.
I only wrapped the raw pointers in Rc's, not the user-facing objects. That way, it's pretty similar to c++'s smart pointers or glib's refptrs

**Comment by rhn** [comment]
Thanks for the explanation. I don't think it's necessarily wrong to track stack lifetimes, `Box` is tracked this way despite data being on the heap. If it doesn't affect performance much, I guess I don't care though :)

**Comment by vhdirk** [comment]
My first version actually did use stack lifetimes. But it was tricky an cumbersome to manage these. What I wanted to achieve was lazy loading of threads within a query. You can only show 20-some threads, so why load all other 20 000? That required storing the Threads iterator somwhere. But, since the lifetime of that iterator as bound to Query, which in its turn was bound to Database, you had to store these things somewhere. And you can't store siblings with dependent lifetimes in a struct. So I simply used Rc's instead.

In the end it's this is just a question of where you want your performance hit. Either you refcount the objects and pass them freely, or you clone data out (notmuch pretty much always keeps pointer ownership) and reopen the db each time you need it.

**Comment by rhn** [comment]
I had some similar issues with lazy loading. While not on the notmuch level - yet - they taught me that it's entirely doable with stack lifetimes.

Rental allows storing [siblings with dependent lifetimes](https://github.com/rhn/notquick/blob/ad9f947b47db911b6d4ac91658dfb56c2916c35e/rust/src/data.rs#L24).

If you're curious about how I dealt with the database being accessed from multiple places - the answer is Arc<Mutex<>>.

**Comment by vhdirk** [comment]
I know about rental, but I decided against using that because it required me to wrap all structs that would use it. That didn't look too clean to me, and I would be surprised if that didn't end up as a performance hit.

**Comment by vhdirk** [comment]
@rhn Just a heads up: I might revert the Rc's back to simple lifetimes, so that you can use it with rental. I've run into some issues regarding multi-threading that I can not easily fix. So, the application you'll be required to use rental (if needed), but it does give you freedom of choice regarding the storage container (being plain, Rc or Arc).

**Comment by rhn** [comment]
Hey, that's cool! The Rc change surprised me back then, as I didn't hit any issues with lifetimes, and I'm sure it will work fine now as well.

**Pull request merged**
